apiVersion: v1
kind: PersistentVolume
metadata:
  name: dudu-pv-volume-md
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/run/desktop/mnt/host/c/school/REALNE_UCENIE/PV_K8S/project_md"
