apiVersion: v1
kind: Service
metadata:
  name: dudu-service
  namespace: duduland-nginx-python-md #!!!namespace
spec:
  selector:
    app: dudu-app #!!!!nazov deployment
  type: NodePort
  ports:
  - name: backend
    port: 8082 
    targetPort: 5000
    nodePort: 30091
  - name: frontend
    port: 8080
    targetPort: 81
    nodePort: 30083